### ISSUE TITLE
Usage this Session delayed updating

### ISSUE THREAD

**Issue by david81** [firstof9/openevse#112]
I just installed the integration via HACS (thanks for updating the built in component) but I'm seeing an issue with the "Usage this Session" sensor. There seems to be a pretty significant delay in the values updating in HA vs what is coming in over the WS.  While the updates posted via WS show increasing values over the session time, the value for the sensor in HA only updates long after the charging session has started or stopped.

I got home at 6:03 p.m. and plugged in but the session usage didn't "reset" until well into the session at 6:39 p.m.. You can see it "started" at around 4 kWh instead of 0. It then didn't update again until 8:40, which is about an hour after the time it would have finished charging. 

![image](https://user-images.githubusercontent.com/918769/204689821-a5171592-b52d-4b3f-8cbe-284e36dc0b9e.png)

If I open up a WS connection, I can see the updates streaming 
`
{
    "amp": 28600,
    "voltage": 240
}{
    "amp": 28600,
    "voltage": 240
}{
    "session_energy": 4126.301667,
    "total_energy": 941.859,
    "wh": 941859
}{
    "amp": 28600,
    "voltage": 240
}{
    "amp": 28600,
    "voltage": 240
}{
    "session_energy": 4130.163889,
    "total_energy": 941.859,
    "wh": 941859
}{
    "amp": 28600,
    "voltage": 240
}{
    "amp": 28600,
    "voltage": 240
}{
    "session_energy": 4133.928611,
    "total_energy": 941.859,
    "wh": 941859
}{
    "amp": 28600,
    "voltage": 240
}{
    "amp": 28600,
    "voltage": 240
}{
    "session_energy": 4137.534722,
    "total_energy": 941.859,
    "wh": 941859
}{
    "amp": 28600,
    "voltage": 240
}
`
Oddly enough, my opening up the WS on my laptop coincides pretty closely to the updating of the sensor in HA, timewise. I also would have checked the sensor in HA around that time. The "after" update also seems to be pretty close to my checking in again after some evening chores. Does this sensor only "pull" data when viewed?

I'm hoping I can use the data via this sensor to feed in to the energy dashboard instead of monitoring the circuit directly, since this is the only thing on that particular circuit. If I can get this reporting consistently, I can save a CT and use it for another circuit.

**Comment by firstof9** [comment]
The sensors don't poll for data, the data is pushed via the websocket.

What firmware version are you running?

**Comment by david81** [comment]
That's what I thought. The other values (Current Power Usage, Charging Current, Ambient Temp, etc) do update in real time. It just seems to be the usage that does not. 

Controller firmware: 8.2.0
WiFi firmware: 4.1.6

**Comment by firstof9** [comment]
As far as I am aware, the session and total usage info doesn't update till the charge is completed/EV disconnected

**Comment by david81** [comment]
The session_energy value is incremented frequently vis the WS connection. You can see the increasing values in the JSON data posted previously. It's not updated as frequently as amp or voltage, but updates go get pushed pretty quickly.

**Comment by firstof9** [comment]
must be updated in 4.1.6 then

**Comment by david81** [comment]
Fair enough. It looks like that attribute doesn't exist in the current API docs. Looking at the PR, it looks like it's posting session_energy, total_energy, and wh every 2 seconds.

**Comment by firstof9** [comment]
I'll have a look when I can get a chance.

**Comment by david81** [comment]
Much appreciated. While you're looking in to this, would it make sense to change the state_class to total_increasing since this will, theoretically, reset with each session?

**Comment by david81** [comment]
What is `total_energy`? I haven't seen that mentioned anywhere, but definitely could have missed it. You should be able to set a `state_class` of `total_increasing` for a `device_class` of `energy`. It's actually the recommended setting for "an energy meter resetting to 0 every time it's disconnected". [Sensor Entity](https://developers.home-assistant.io/docs/core/entity/sensor/#entities-representing-a-total-amount )

**Comment by firstof9** [comment]
https://github.com/firstof9/openevse/blob/main/custom_components/openevse/const.py#L85-L98

The sensors are already setup properly for the state and device classes.
