### ISSUE TITLE
FR: add sensor.openevse_pilot

### ISSUE THREAD

**Issue by fhteagle** [firstof9/openevse#139]
Consider adding a sensor.openevse_pilot that would monitor and report changes of the /status endpoint value "pilot". This is the actual amount of amps being advertised to the car by the unit after all of the overrride, claims, etc logic has been completed. In other words, it is the ground truth as to what the unit is really really doing.

**Comment by firstof9** [comment]
This is already handled by the `sensor.openevse_current_capacity` sensor.
