### ISSUE TITLE
Usage this session sensor not updating

### ISSUE THREAD

**Issue by silviudc** [firstof9/openevse#150]
Seems like the "Usage this session" is not updating anymore as of 2.1.9 update.
If I do a reload integration the value then refreshes, but not continuously as before, not sure if just me or others seeing this too?

Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

**Comment by firstof9** [comment]
Updating fine here:

![image](https://user-images.githubusercontent.com/1105672/219971041-936758f1-a308-4248-9ec5-28d0da801f3f.png)

**Comment by firstof9** [comment]
> Looks to me like update of session kWh only happens when charging finishes (actual charge current goes to 0 or the car disconnects).

That's how it's sent via the websocket.

**Comment by david81** [comment]
It looks like some updates are coming in the next OpenEVSE WiFi firmware build for energy stats https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/556

**Comment by david81** [comment]
It already is updating at more frequent intervals via the `session_energy` attribute

**Comment by firstof9** [comment]
`session_energy` is used in the latest version, enjoy!

**Comment by david81** [comment]
Forgive me for bringing it up again, but I think the state_class on the session usage really should be total_increasing vs total. Given that this value will start at zero for each new session and will only ever increase based on the power consumed in the session, that seems the most appropriate. Using total will cause HA to see the start of a new session as a net reduction in the consumption.

**Comment by firstof9** [comment]
Ah you're right, I just reviewed the class in the dev docs (it wasn't there previously). I'll update that. :+1:
