### ISSUE TITLE
Wrong unit for Shaper Power

### ISSUE THREAD

**Issue by dark-nico** [firstof9/openevse#187]
Hello, 

The unit for the shaper power (live power) is wrong. 
It should be watt and not amps. 

I think line 235 on custom_components/openevse/const.py should be changed : 

native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE, --> native_unit_of_measurement=POWER_WATT,

Have a nice day. 

Nicolas

**Comment by firstof9** [comment]
Thanks! I'll adjust that.
