### ISSUE TITLE
Session usage resetting when it shouldn't

### ISSUE THREAD

**Issue by david81** [firstof9/openevse#194]
It seems that the updated Session Usage sensor (big thanks here) is not quite 100%. I'm not sure what's causing it, but it seems to be resetting back to zero if charging completes then starts again. I noticed it today when HA was reporting unusually high usage. 

I plugged in when I got home last night, and things went well. This morning, the automated climate control kicked on to preheat the vehicle, which draws power from the charger and there as a momentary blip that set the session usage back to 0 but then rebounded and picked up where it left off. Since the sensor is setup as total_increasing (correct since it should reset with each session) this caused HA to report all of yesterday's usage along with the small amount from this morning together in today's numbers. Not sure if this is coming from the integration or from the unit itself. 

![image](https://user-images.githubusercontent.com/918769/227339208-009109fa-6ac0-4b9e-a819-a9ae34b3fc53.png)

**Comment by david81** [comment]
I should add, this is the first time this has happened this week, despite multiple other days with the same charging behavior. 

![image](https://user-images.githubusercontent.com/918769/227340747-4e025aec-ef51-4090-8069-49ae676f9538.png)

**Comment by firstof9** [comment]
This may be a firmware bug.
