### ISSUE TITLE
Errors in HA with new pre-release

### ISSUE THREAD

**Issue by omriasta** [firstof9/openevse#20]
I am getting 2 errors which appear to be coming up frequently (see # of occurrences):
```
This error originated from a custom integration.

Logger: custom_components.openevse
Source: custom_components/openevse/__init__.py:225
Integration: OpenEVSE
First occurred: 6:06:40 AM (1276 occurrences)
Last logged: 11:19:01 AM

Could not update status for available_current
Could not update status for smoothed_available_current
```

AND
```
This error originated from a custom integration.

Logger: custom_components.openevse
Source: custom_components/openevse/__init__.py:241
Integration: OpenEVSE
First occurred: 6:06:40 AM (638 occurrences)
Last logged: 11:19:01 AM

Could not update status for divert_active

```

**Comment by firstof9** [comment]
Those are technically not errors, I'll adjust the logging on those messages down to info level.

**Comment by firstof9** [comment]
Should be sorted in `2.0.12`

**Comment by jcsogo** [comment]
I also need to take a look at these, because those fields appear in the [documentation](https://openevse.stoplight.io/docs/openevse-wifi-v4/b3A6MjA2MTYyMzE-get-the-evse-status) of the OpenEVSE Wifi Module but somehow it looks like that they are not being published. I need to understand if these only get published if the divert mode is enabled and active.

**Comment by omriasta** [comment]
> Should be sorted in `2.0.12`

still getting the divert_active error in 2.0.12:

```
This error originated from a custom integration.

Logger: custom_components.openevse
Source: custom_components/openevse/__init__.py:241
Integration: OpenEVSE
First occurred: 12:29:36 PM (3 occurrences)
Last logged: 12:30:02 PM

Could not update status for divert_active
```

**Comment by firstof9** [comment]
Keep in mind that these fields do not exist in the firmware v3 and lower.
You can hide the message by setting the logging for openevse to `warning` or `error`.

**Comment by omriasta** [comment]
I am on firmware v4.1.0. how does one change logging level for openevse?

**Comment by firstof9** [comment]
In your `configuration.yaml` you'll need something along these settings for the logger:

```yaml
logger:
  default: warning
  logs:
    custom_components.mail_and_packages: error
```

**Comment by firstof9** [comment]
Sorry I didn't notice the binary sensors were still reporting on warning level as well, `2.0.13` should fix this fully now.

**Comment by ruimarinho** [comment]
@firstof9 I'm getting on v7.1.3.3P with WiFi version 4.1.2.dev:

```
2022-05-02 21:00:16 INFO (MainThread) [custom_components.openevse] Could not update status for divert_active
2022-05-02 21:00:16 INFO (MainThread) [custom_components.openevse.binary_sensor] binary_sensor [divert_active] not supported.
2022-05-02 21:00:30 INFO (MainThread) [custom_components.openevse] Could not update status for divert_active
2022-05-02 21:00:30 INFO (MainThread) [custom_components.openevse.binary_sensor] binary_sensor [divert_active] not supported.
2022-05-02 21:00:46 INFO (MainThread) [custom_components.openevse] Could not update status for divert_active
2022-05-02 21:00:46 INFO (MainThread) [custom_components.openevse.binary_sensor] binary_sensor [divert_active] not supported.
```

Is it supposed to be the case?

**Comment by firstof9** [comment]
yup those are just info, not errors.

**Comment by ruimarinho** [comment]
Would it be possible to change the logging level to debug? If it's not something I can act one and since it's logged every few seconds, I think it would create a better experience.

**Comment by firstof9** [comment]
I can do this, but I do question why you logging on such a low level?
I believe the default logging for Home Assistant is `error`

**Comment by ruimarinho** [comment]
I believe there is actually an issue -- do you want me to open an new issue to track this?

v7.1.3.3P with WiFi version 4.1.2.dev:

```
2022-05-12 23:48:00 ERROR (MainThread) [openevsehttp] Invalid value for divertmode: normal
2022-05-12 23:48:00 WARNING (MainThread) [custom_components.openevse.select] Could not set status for openevse Divert Mode error:
```

**Comment by firstof9** [comment]
Yes please.
Thank you.
