### ISSUE TITLE
Minor Request: Total Usage decimal/rounding

### ISSUE THREAD

**Issue by fhteagle** [firstof9/openevse#200]
At some point with the changes to EnergyMeter features in GUI v2, my HA instance started reporting a very high number of decimal places for "Total Usage" for both OpenEVSEs (e.g. 1,037.680051 kWh ). The session usage is reported with 2 decimal places. Could we get Total Usage rounded to the same number of decimals? 

Thanks.

**Comment by firstof9** [comment]
You can actually set this in Home Assistant.

![image](https://user-images.githubusercontent.com/1105672/227795935-86bcc57b-5d15-42dc-8a26-e6f0be0c3bc2.png)
