### ISSUE TITLE
 integration does not show up in the add list. 

### ISSUE THREAD

**Issue by jjlink** [firstof9/openevse#22]
I added the openevse folder and files to the custom components folder. Rebooted HA and tried to add the integration however it does not show up in the list. 

I also see this error message in the log file:
ERROR (MainThread) [homeassistant.components.sensor] The openevse platform for the sensor integration does not support platform setup. Please remove it from your config.

**Comment by firstof9** [comment]
Sounds like you didn't extract it into your configuration directory properly.

**Comment by jjlink** [comment]
Yes, I just installed it via HACS. Thanks!

**Comment by jjlink** [comment]
Closing issue.

**Comment by pepelillo** [comment]
Same issue but different log:
 Logger: openevsehttp
Source: custom_components/openevse/config_flow.py:60
Integration: OpenEVSE
First occurred: 10:48:32 (2 occurrences)
Last logged: 10:48:32

    Non JSON response:
    Authentication error:

But How can I configure authentication if I can't add the integration in the list and configure it?
