### ISSUE TITLE
Max current reset and sleep mode

### ISSUE THREAD

**Issue by diybateriaslifepo4** [firstof9/openevse#225]
Hi, a few days ago I installed your fabulous integration, but I'm noticing a problem when changing settings, I see that with each change the max current is always set to the maximum automatically, and that there are options that they do not work correctly, for example to activate the sleep mode you have to hit it several times.

I don't know if it's a configuration error on my part or it's simply working properly, but I think something is wrong, 

https://github.com/firstof9/openevse/assets/80992172/9d29137c-d33a-438b-9d82-cc40307b8dc8

**Comment by diybateriaslifepo4** [comment]
![Screenshot_20230617_111039](https://github.com/firstof9/openevse/assets/80992172/512595e9-b207-4e73-a7e7-69e39a7ffe6e)

**Comment by firstof9** [comment]
The switch will flip back if the EVSE doesn't update (ack) that the switch was flipped.

**Comment by diybateriaslifepo4** [comment]
What could be the cause? there are two problems, one the flip back switch, and another that the max current is set to 32A in each action, any solution for these annoying problems?

**Comment by firstof9** [comment]
Looks like you have a manual override already setup, so it's toggling that off first, then you have to flip it a 2nd time to get the sleep to engage.

It's not ideal behavior, and I need to do some tests to see if setting the current limit to `0` will sleep the EVSE.

**Comment by diybateriaslifepo4** [comment]
the manual override is automatically activated whenever I change the max current, it is only deactivated when the maximum power is selected...

**Comment by firstof9** [comment]
Correct, that is the recommended way to change the max current.

**Comment by diybateriaslifepo4** [comment]
So can anything be done to fix this problem? So I can't control the charger with automations because it doesn't do what I want...

**Comment by firstof9** [comment]
Use the `openevse.set_override` service call for automations.

**Comment by firstof9** [comment]
I need to update the wording but setting the state to `disabled` blocks charging.

**Comment by diybateriaslifepo4** [comment]
Do you think you'll be able to do it someday not too far away? It would be very useful for me (and I understand for many more people), thank you!

**Comment by diybateriaslifepo4** [comment]
I have updated and the same thing continues to happen, the max current restarts at 32A and the sleep is not activated at first, for me if it is an error 😭

**Comment by firstof9** [comment]
How are you calling the `openevse.set_override` service?

**Comment by diybateriaslifepo4** [comment]
I do not call the set override, the manual override switch changes on its own. That I try to put the sleep mode and it does not work at first, you just have to watch the video for see the problem 🤔

**Comment by firstof9** [comment]
It's working as it should, if you need to automate disabling/enabling the charge, use the service call.
