### ISSUE TITLE
Some entities not syncing

### ISSUE THREAD

**Issue by cyberelectronics** [firstof9/openevse#233]
Hi,
I have some entities which are not syncing, so I need to reload the config entry periodically if I want to see updated values.
Example entities: 
sensor.openevse_usage_this_session
sensor.openevse_charge_time_elapsed 
![reload](https://github.com/firstof9/openevse/assets/37063865/1192f913-4fab-4d03-942b-30aca0ce93e1)

**Comment by firstof9** [comment]
Those entities are updated from the OpenEVSE via the websocket. If you are running older firmware they'll update and the end of the charge. Newer firmware updates them during the charge now.

**Comment by cyberelectronics** [comment]
Yes, it's possible, as I have an older fw.
Thank you!
