### ISSUE TITLE
FR: Provide Self Production data via Post 

### ISSUE THREAD

**Issue by davethetallguy** [firstof9/openevse#237]
OpenEVSE 4.2.2 supports posting available current for Eco mode [using http push.](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/master/docs/user-guide.md#using-http)

While there are other ways of tinkering with the charging limits, I already have a sensor in HA (provided by Emporia in my case) which shows the net flow of power to/from the grid. Can a feature be added to simply post that information to OpenEVSE?  I'm envisioning a field to add a sensor like "sensor.sce_meter_net_123_1min", and post that to EVSE on update.

Bonus points for a checkbox that reverses the +/- sign, in case someone is using a sensor that reads in the opposite direction.

Notes:
1) Yes, MQTT does this now, however I have direct integrations for everything else that used to use MQTT, so OpenEVSE is the only device depending on MQTT messages. I'd rather not run MQTT for a one-off. 
2) Yes, I probably can (and might in the interim) write an automation that makes the post for me, but it would be elegant to see it wrapped into your integration, assuming I haven't missed something that you already provide.

Thanks again for a great add-on. I've been EV-less for a few months, just got another one yesterday, and am spinning up my related systems again.

**Comment by firstof9** [comment]
I'll see what I can come up with.
