### ISSUE TITLE
openevse_Usage this Session (aka "session_energy") does not update consistently with other entities

### ISSUE THREAD

**Issue by davethetallguy** [firstof9/openevse#24]
HA Version 2021.12.9
Awesome firstof9/openevse version 2.0.13
OpenEVSE version 7.1.3
OpenEVSE WiFi version 4.1.1

I'm trying to use a [utility meter](https://www.home-assistant.io/integrations/utility_meter/) in HA to identify how much of my monthly electric bill is from car charging. I want two active meters - current session and monthly (billing cycle) total.

To use Utility Meter one needs to provide a source consumption meter, in this case I intended to use openevse_Usage this Session for the current session.

After getting unexpected results, I looked closer at openevse_Usage this Session, and realized updates were showing up several minutes later, if at all. 

For comparison, I pulled real time stats using [openEVSE curl command line](https://openevse.stoplight.io/docs/openevse-wifi-v4/b3A6MjA2MTYyMzE-get-the-evse-status), and in the response the "session_energy" data (in Wh, not kWh) is updating in real time.  

All other session related sensors, e.g. openevse_Charging Current and openevse_Charging Status update within a few seconds of changes in status.  

I can do math and [integrals](https://www.home-assistant.io/integrations/integration/) based on openevse_Charging Current, but it would be great if the Usage This Session sensor were updating in real time. As I write this issue, it is at least 16 minutes behind.

**Comment by firstof9** [comment]
Correct the websocket doesn't update the session usage regularly as it should, I've already put in a bug to the OpenEVSE team regarding this. To utilize the utility meter in Home Assistant as you're wanting its best to use the `total_usage` sensor as this is always incrementing and doesn't roll backwards unless you reset the OpenEVSE unit.

This is also how I monitor it currently as well.

**Comment by davethetallguy** [comment]
total_usage only updates at the end of the session though, correct? The problem is that my utility has up to 6 different tariffs, so I need to know the utilization more or less in real time. Otherwise it all gets charged to the tariff in effect when the session ends, usually when I remove the charging cable, which by intent is often a different rate than when the charging actually took place. 

I'll try creating my own real time kWh meter and post here if I come up with something useful. 

Hopefully OpenEVSE can sort the websocket issue soon.

**Comment by drobtravels** [comment]
I also would like to have realtime kwh.

Right now I use the [Riemann sum integral](https://www.home-assistant.io/integrations/integration/) but it seems buggy / inaccurate.

```
-  platform: integration
    name: openevse_calculated_energy
    unit_prefix: k
    source: sensor.openevse_power
```

**Comment by firstof9** [comment]
> total_usage only updates at the end of the session though, correct?

AFAIK, the session and total usage should update as time progresses while charging.

**Comment by davethetallguy** [comment]
> AFAIK, the session and total usage should update as time progresses while charging.

That has not been my experience, and when I tested it this morning (day off project!) total_usage pretty clearly only updated when I unplugged my car. This includes all presentations - the statistics in your integration, via curl, or using the OpenEVSE page.



> Right now I use the [Riemann sum integral](https://www.home-assistant.io/integrations/integration/) but it seems buggy / inaccurate.

I saw a recommendation to use the "left" method, which I think is because utilization is a quick spike on or off, but someone who understands calculus better than I do might know better.

In any case, I ran several short-duration tests (5-10 minute charging cycles) and compared the results from the Riemann Sum Integral and they were within very close proximity to the data coming directly from OpenEVSE, like within 0.01 kWh.  

@drobtravels what kind of error rate do you think you're seeing? 

Here's what my integration sensor looks like:

```
  - platform: integration
    source: sensor.openevse_charging_watts_computed
    name: "EVSE Running kWh Computed"
    unit_prefix: k
    round: 3
    method: left
```
For completeness, here's my template sensor:
```

template:
  - sensor:
      - name: "Openevse Charging Watts Computed"
        unique_id: "openevse_charging_watts_computed"
        state: "{{ (states('sensor.openevse_charging_current') | float(0) * states('sensor.openevse_charging_voltage') | float(0) )| round(0) }}"
        device_class: "power"
        unit_of_measurement: W
        state_class: measurement

```

**Comment by firstof9** [comment]
> That has not been my experience, and when I tested it this morning (day off project!) total_usage pretty clearly only updated when I unplugged my car.

Yes that is the _should_ part. Per the API docs the `total_usage` is supposed to update as well.
From what I read they are working on all this right now.

**Comment by drobtravels** [comment]
> I saw a recommendation to use the "left" method, which I think is because utilization is a quick spike on or off, but someone who understands calculus better than I do might know better

Hmm.. that might be my issue.  I thought I had tried it previously but may be thinking of a difference device.  I see huge spikes off by 30+kwh.  Glad to hear you are not... I changed mine to `left`.

**Comment by davethetallguy** [comment]
Seems like we're done here for now though, pending the update to OpenEVSE, as it's their bug.  I'll watch over there as well.

Thanks for the assist.
