### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by Lezney** [firstof9/openevse#269]
Hi there, first and foremost thank you for this integration.

Unfortunately I haven't been able to get it working. I'm hoping you can give me an idea of where I'm going wrong. Here's a look at my configuration:

![image](https://github.com/firstof9/openevse/assets/149842068/6e7463c6-8713-47b4-8e26-f53271ab9e36)

But it doesn't appear under integrations:

![image](https://github.com/firstof9/openevse/assets/149842068/ea5459bb-1b09-4d36-9b73-aeab6b45c62f)

Thanks in advance for your assistance.

**Comment by firstof9** [comment]
It is best to add the repo to HACS and install it that way.

**Comment by Lezney** [comment]
> It is best to add the repo to HACS and install it that way.

Okay how do I do that?

**Comment by firstof9** [comment]
I've updated the [Readme with links and instructions](https://github.com/firstof9/openevse#installation-via-hacs-recommended).

If something isn't clear, please let me know so I can update the instructions as well.

Thanks.

**Comment by Lezney** [comment]
Thank you for the update. I don't see an "install" button, but I think this is correct?:

![image](https://github.com/firstof9/openevse/assets/149842068/afae4934-c5ac-4518-aaff-0e1dfb141544)

Also there's no "configuration" button but I assume you meant the "settings" button. But it doesn't appear in the integrations either.

![image](https://github.com/firstof9/openevse/assets/149842068/f04ade27-2a94-4949-afb7-2cef77d4efc6)

**Comment by firstof9** [comment]
Oops you added it as a plugin not integration, redo the HACS part but select "Integration", it should look like this:

![image](https://github.com/firstof9/openevse/assets/1105672/49a9afee-9d85-4ac7-9658-2d7edcc371e9)

![image](https://github.com/firstof9/openevse/assets/1105672/0458f956-e032-4501-83fc-efe33e497768)

Then make sure to install it from HACS, using the search feature at the top of HACS and enter "openevse", then install it like you installed that (what looks like) Tesla integration.

**Comment by Lezney** [comment]
Sweet, that did it, thanks again! You might update the verbiage in your documentation with the above and add quotes around "integration", that might help to clear it up.

**Comment by firstof9** [comment]
Thanks for the feedback, I've made some changes to the readme that should help make it clearer. Thanks!
