### ISSUE TITLE
[FR] Implement all datapoints for HTTP POST sensor data push

### ISSUE THREAD

**Issue by denisfrench** [firstof9/openevse#290]
I have found direct push of my grid import/export sensor to my OpenEVSE by the integration handy, which enabled me to remove the intermediate steps of an automation publishing to MQTT and setting my OpenEVSE to subscribe to that topic.

I would similarly like to be able to directly push my grid voltage sensor to my OpenEVSE.

Probably there are other use cases that would benefit from implementation of all the datapoints available to be sent via HTTP POST, as per the documentation (https://openevse.stoplight.io/docs/openevse-wifi-v4/21c8a9ac8dd46-update-external-data-to-evse-status).

Thanks for all your work on this integration so far 🙂

**Comment by firstof9** [comment]
I'll have this released when HA 2024.1.0 drops on the 3rd.
