### ISSUE TITLE
Failed to call service switch/turn_on. unknown error

### ISSUE THREAD

**Issue by nrp929** [firstof9/openevse#301]
Hey Chris,
I got the newest OpenEVSE that has the 3.5" graphical display. Evidently, they're using the Elecrow_ESP32_HMI branch (https://github.com/OpenEVSE/openevse_esp32_firmware/tree/elecrow_esp32_hmi) and some of the functions of your integration don't seem to be working. 
Manual override switch, max current, sleep mode switch and Solar PV divert switch don't work. 

[home-assistant_2024-02-19T03-41-40.188Z.log](https://github.com/firstof9/openevse/files/14326039/home-assistant_2024-02-19T03-41-40.188Z.log)

> This error originated from a custom integration.
> 
> Logger: openevsehttp.__main__
> Source: custom_components/openevse/__init__.py:290
> Integration: OpenEVSE (documentation, issues)
> First occurred: 7:05:45 PM (3 occurrences)
> Last logged: 7:29:12 PM
> 
> Non-semver firmware version detected.
> 

> Logger: homeassistant.components.websocket_api.http.connection
> Source: components/websocket_api/commands.py:240
> Integration: Home Assistant WebSocket API (documentation, issues)
> First occurred: 7:15:30 PM (4 occurrences)
> Last logged: 7:31:28 PM
> 
> [139660620204096]
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
>     response = await hass.services.async_call(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
>     response_data = await coro
>                     ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
>     return await target(service_call)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
>     single_response = await _handle_entity_call(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
>     result = await task
>              ^^^^^^^^^^
>   File "/config/custom_components/openevse/switch.py", line 102, in async_turn_off
>     await getattr(self._manager, self.toggle_command)()
>   File "/usr/local/lib/python3.12/site-packages/openevsehttp/__main__.py", line 325, in divert_mode
>     raise UnsupportedFeature
> openevsehttp.exceptions.UnsupportedFeature

> 
> This error originated from a custom integration.
> 
> Logger: openevsehttp.__main__
> Source: custom_components/openevse/select.py:93
> Integration: OpenEVSE (documentation, issues)
> First occurred: 7:36:57 PM (1 occurrences)
> Last logged: 7:36:57 PM
> 
> Error 400: RAPI_RESPONSE_BLOCKED

**Comment by firstof9** [comment]
```
2024-02-18 19:40:07.918 WARNING (MainThread) [openevsehttp.__main__] Non-semver firmware version detected.
```

What firmware version is your unit reporting?

**Comment by nrp929** [comment]
![image](https://github.com/firstof9/openevse/assets/101362764/8bdf24f5-d01c-4ea2-998f-420b36903239)

**Comment by nrp929** [comment]
Sorry for my ignorance, I'm pretty new to all this. 

None of the features I tried to use should be unsupported. I'm able to view and make changes to all the features I attempted using your integration on the openEVSE's web portal. For example, the solar divert switch is accessible and I can turn it on and off by using the openEVSE's web portal. But when I tried to use the switch in your integration on Home Assistant, it says it gives me an error. Another example is the max current option. I can't change it in home assistant but I can change it in the web portal.

Lastly, I tried unsuccessfully several times to feed solar and grid data to the openEVSE. Initially, I had mqtt off and then I tried again with it on. Maybe I'm not using the correct topics under mqtt. Now I'm just feeding it using the home assistant's mqtt broker add on.

**Comment by firstof9** [comment]
Those features get "unsupported" flagged due to your wifi firmware showing up wrong.
The integration is expecting a proper sem-version for the wifi firmware. ie: `4.3.1` or `2.3.1` etc.

**Comment by nrp929** [comment]
Ah, that makes sense. Is there a way for me to change the sem-version using File Editor in Home Assistant?

**Comment by firstof9** [comment]
Sorry, no, that's baked into the firmware's bin file that you flash to the device.
You could ask the OpenEVSE guys in their repo how to adjust it then compile it.

**Comment by nrp929** [comment]
From what I understand from the other Chris (at OpenEVSE), it should be merged with the master soon. So hopefully, the situation resolves itself then.

**Comment by nrp929** [comment]
Thank you for taking the time to look into this today!

**Comment by nrp929** [comment]
openEVSE v5.1.0 firmware update fixed issue.
