### ISSUE TITLE
No simple way of forcing a deterministic On or Off

### ISSUE THREAD

**Issue by karora** [firstof9/openevse#332]
## Background
I am trying to use this extension to cover several situations, but am finding it very difficult to get deterministic results:

1. In the small hours of the morning, I want to enable the charger to charge the car for a couple of hours.  Since this will be pulling from the grid, I want to do it as slowly as possible.
2. When the sun is shining (and the house battery is above 75%, and the panels are generating 2kW or more) I want to enable the car to charge as slowly as possible.
3. When the house battery is above 85% and the panels are generating 3kW or more I want to enable the car to charge faster.

So my goals are essentially to have Home Assistant send commands like:
1. Enable charging at 6 amps.
2. Disable charging
3. Set charging limit to X amps.

But I seem to be bashing my head against too much smarts.  To be fair this is probably me being an idiot, and not an issue with this software...

## What I Have Home Assistant Configured to Run

For (1) I have the following actions to Run:

- Turn Off Solar PV Divert
- Turn Off Sleep Mode (new)
- Turn On Manual Override
- Change max current option to 6

If I omit any of these steps I seem to run into problems with the charge not starting.

For (2) then, it would seem that I should turn off manual override, but that doesn't work, and in fact if I do that it increases the charge rate to whatever is the maximum configured in the EVSE settings (i.e. the previously set 'max current' option is lost. In fact I have to:

- Turn Off manual override
- Turn On Sleep Mode (new)
- Turn On manual override

That was kind of unexpected!

For (3), thankfully the "Change max current option to X" does seem to work, although the OpenEVSE itself appears to handle odd numbers for current as well as even ones, but there's no way to set 7,9,11 from Home Assistant. I can live with that, though it would be nice to step the current up as the sun gets brighter.

I've also tried letting the OpenEVSE adjust itself with the Solar PV Divert option and feeding current generation into it using MQTT but that tends to overcommit to charging the car and discharges the home battery which I prefer to save to get us through the peak electricity rates that arrive just after sunset.

## My Questions

- Would you be amenable to PRs to provide a couple of simpler "Enable / Disable Charging" commands?
- Where should I look first to implement those?

Thanks for your work on this.  It is greatly appreciated!

**Comment by Oinq** [comment]
*When the battery is above 85% and the panels are generating 3kW or more I
want to enable the car to charge faster.*

So you want to charge faster when you should charge slower?
Batteries don't like heat; the faster you charge, the warmer you make, and
much probably the car will reduce the charging speed above 85% or so...
I always charge at 6A, and my 2016 EV still has 100%SOH.

This is not answering your questions, but I thought you might not know this
info.


Best regards
-----

Cumprimentos   /   Kind Regards  /  Met vriendelijke groeten / Sincères
amitiés
Nuno Leitão
https://www.linkedin.com/in/nunocasanovaleitao/

**Comment by karora** [comment]
> *When the battery is above 85% and the panels are generating 3kW or more I want to enable the car to charge faster.* So you want to charge faster when you should charge slower? Batteries don't like heat; the faster you charge, the warmer you make, and much probably the car will reduce the charging speed above 85% or so... I always charge at 6A, and my 2016 EV still has 100%SOH. This is not answering your questions, but I thought you might not know this info.

This is irrelevant to my questions, of course, but in the interests of completeness you misunderstood me there: I mean I want to charge my car faster when my *house* batteries are more full.  There's a second thing too, in that my house is using LFP batteries which can be deep cycled much more effectively than the batteries you're thinking of, such as the ones in my car.  The car is configured to stop charging at the manufacturers recommended level.  Unfortunately I can't read the car's state of charge in Home Assistant, but I have a ton of detail about how my solar power setup is operating.

**Comment by karora** [comment]
Just playing around with the OpenEVSE API, I find I can very reliably enable / disable charging with a single API call, like:

```
$ curl --request POST   --url http://openevse.local/override   --header 'Accept: application/json'   --header 'Content-Type: application/json'   --data '{ "state": "enabled", "auto_release": true, "charge_current": 6, "max_current": 12}'
 
$ curl --request POST   --url http://openevse.local/override   --header 'Accept: application/json'   --header 'Content-Type: application/json'   --data '{ "state": "disabled", "auto_release": true, "charge_current": 6, "max_current": 12}'
```

which seems it would achieve exactly what I need - I just need to know where to make the changes, but I can probably figure that out tomorrow and propose a PR.

**Comment by firstof9** [comment]
I'd suggest using the service call: `openevse.set_override` in your automation(s), they use the override endpoint.

**Comment by karora** [comment]
Ah, perfect!  Thanks for your help :-)
