### ISSUE TITLE
Deprecated constants.

### ISSUE THREAD

**Issue by ve6rah** [firstof9/openevse#334]
Logger: homeassistant.const
Source: helpers/deprecation.py:206
First occurred: 9:48:37 AM (7 occurrences)
Last logged: 9:48:37 AM

ENERGY_KILO_WATT_HOUR was used from openevse, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'openevse' custom integration
LENGTH_METERS was used from openevse, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.METERS instead, please report it to the author of the 'openevse' custom integration
POWER_WATT was used from openevse, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please report it to the author of the 'openevse' custom integration
TEMP_CELSIUS was used from openevse, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'openevse' custom integration
TIME_MINUTES was used from openevse, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please report it to the author of the 'openevse' custom integration

**Comment by firstof9** [comment]
These were updated quite a few releases ago.
What version of HA and OpenEVSE are you using?

**Comment by ve6rah** [comment]
That's interesting, HACS was not showing an update, but I was in fact several versions out of date, removing and readding the repository seems to have solved it.

**Comment by firstof9** [comment]
HACS weirdness.
