### ISSUE TITLE
[Bug]: Vehicle Battery Level, Vehicle Charge Completion and the Vehicle Range not updating

### ISSUE THREAD

**Issue by firstof9** [firstof9/openevse#366]
### The problem

Vehicle Battery Level, Vehicle Charge Completion and Vehicle Range are always unavailable

### What version of Home Assistant?

core-2024.8.0

### What version of OpenEVSE?

2.1.40

### Anything in the logs that might be useful for us?

```txt
{"divert_update":0,"grid_ie":-1692}
{"voltage":238.1100006}
{"session_elapsed":1589,"session_energy":1799.576252,"total_energy":2875.618971,"total_day":6.286456882,"total_week":66.34828806,"total_month":82.89989152,"total_year":137.7844404,"total_switches":3024}
{"amp":17160,"voltage":238.11,"power":4085.9676}
{"evse_connected":1,"amp":17160,"voltage":238.11,"power":4085.9676,"pilot":18,"max_current":32,"temp":368,"temp_max":368,"temp1":false,"temp2":368,"temp3":false,"temp4":false,"state":3,"status":"active","flags":1344,"vehicle":1,"colour":6,"manual_override":1,"freeram":171136,"divertmode":1,"srssi":-71,"time":"2024-08-10T20:43:16Z","local_time":"2024-08-10T22:43:16+0200","offset":"+0200","uptime":23670,"session_elapsed":1589,"session_energy":1799.576252,"total_energy":2875.618971,"total_day":6.286456882,"total_week":66.34828806,"total_month":82.89989152,"total_year":137.7844404,"total_switches":3024,"elapsed":1589,"wattsec":6478474.506,"watthour":2875618.971}
{"shaper":1,"shaper_live_pwr":-16,"shaper_smoothed_live_pwr":-16,"shaper_max_pwr":8400,"shaper_cur":52.49165407,"shaper_updated":true}
{"amp":17160,"voltage":238.11,"power":4085.9676}
_pause_timer = 0
{"divert_update":0,"grid_ie":-1717}
{"voltage":238.1999969}
{"amp":17160,"voltage":238.2,"power":4087.512}
{"shaper":1,"shaper_live_pwr":-41,"shaper_smoothed_live_pwr":-41,"shaper_max_pwr":8400,"shaper_cur":52.6100021,"shaper_updated":true}
{"battery_range":246,"vehicle_state_update":0}
{"battery_level":95,"vehicle_state_update":0}
{"time_to_full_charge":1500,"vehicle_state_update":0}
{"amp":17160,"voltage":238.2,"power":4087.512}
```

**Comment by firstof9** [comment]
Technically this will be an update to the library used to parse the websocket/API data.

**Comment by zerodur12** [comment]
If it can help using MQTT explorer the topic publish with MQTT by the charger about the vehicule are:
battery_level = 100
vehicle_state_update = 0
battery_range = 259
time_to_full_charge = 300

Thank for the investigation

**Comment by firstof9** [comment]
This should work in version `2.1.44` for you.

**Comment by zerodur12** [comment]
Thank for the update now the Vehicle Battery Level, Vehicle Charge Completion and Vehicle Range are available
But there still a probleme of unit in HA:
![image](https://github.com/user-attachments/assets/478d6a2b-954c-4c55-be98-db508c447ebf)
the 300 min should be 300 s or 5min
the vehicul range 0.267 km should be 267 km

**Comment by firstof9** [comment]
Yikes, working on it now.

**Comment by firstof9** [comment]
`2.1.45` should fix that. Thanks!

**Comment by zerodur12** [comment]
Thanks for the great job
Now the unit are ok 
if I can I suggest 2 improvements:
1/ for Vehicle Charge Completion rather than display the time in s in HA, display it in “hh:mm:ss” like in the OpenEVSE UI which is more convenient numbers to understand Vehicle Charge Completion time
2/ For the Vehicle Range unit, if possible, this unit has to be define by the unit define in the OpenEVSE UI (km or miles) see figure below with your last update the unit is km (fine for me) whatever you put (km or miles) in the OpenEVSE UI

![image](https://github.com/user-attachments/assets/9c3e6660-163b-4831-9101-d634c82da819)

**Comment by firstof9** [comment]
> 1/ for Vehicle Charge Completion rather than display the time in s in HA, display it in “hh:mm:ss” like in the OpenEVSE UI which is more convenient numbers to understand Vehicle Charge Completion time

I can try, but I have to convert the data from OpenEVSE into a timestamp, not super hard, but I can see what I can do.
Would be nice if OpenEVSE spit out timestamps in another key, would make things tons easier.

> 2/ For the Vehicle Range unit, if possible, this unit has to be define by the unit define in the OpenEVSE UI (km or miles) see figure below with your last update the unit is km (fine for me) whatever you put (km or miles) in the OpenEVSE UI

I don't think that configuration variable comes in over any of the endpoints so I have no way to read that into Home Assistant.

**Comment by zerodur12** [comment]
> > 1/ for Vehicle Charge Completion rather than display the time in s in HA, display it in “hh:mm:ss” like in the OpenEVSE UI which is more convenient numbers to understand Vehicle Charge Completion time
> 
> I can try, but I have to convert the data from OpenEVSE into a timestamp, not super hard, but I can see what I can do. Would be nice if OpenEVSE spit out timestamps in another key, would make things tons easier.

It is nice thing to have if to complicatedd I can manage also by template sensor in HA to transform it in hh:mm:ss 



> > 2/ For the Vehicle Range unit, if possible, this unit has to be define by the unit define in the OpenEVSE UI (km or miles) see figure below with your last update the unit is km (fine for me) whatever you put (km or miles) in the OpenEVSE UI
> 
> I don't think that configuration variable comes in over any of the endpoints so I have no way to read that into Home Assistant.

For this point I see that in HA we can override the unit of this sensor so if somebody need to replace km to mi it can be done manually in HA which is ok I think.

![image](https://github.com/user-attachments/assets/65d9e60a-09f2-4d87-94ef-40283ea301a7)

**Comment by firstof9** [comment]
I'll see about making the timestamp a separate sensor, that way someone can pick however they want to see it.
