### ISSUE TITLE
[Feature Request]: number instead of select for charge rate

### ISSUE THREAD

**Issue by KipK** [firstof9/openevse#393]
### The feature

I don't know what are the implications on this, neither why it was decided first to use a select for charge rate, but I think it would be more approriated to have the select.openevse_charge_rate entity replaced by a number.openevse_charge_rate

Using a slider on UI gives a better UX than a selector, and stays in sync with Openevse UX.

Best

**Comment by darrendavid** [comment]
Has this changed? I see that `select.openevse_max_current` is no longer available in the HA integration.

**Comment by firstof9** [comment]
> Has this changed? I see that `select.openevse_max_current` is no longer available in the HA integration.

Please review the release notes: https://github.com/firstof9/openevse/releases/tag/2.1.46

**Comment by KipK** [comment]
Hey

I'm testing your commit. Thanks for this.

The number slider is sluggish as it waits for update before moving. 
I think there's a way to make this entity optimistic,
This way slider takes current setted value, and will update if needed when state return back instead of waiting for it.

Also if you want to stay in synch with OpenEVSE UI behavior, when the number is set back to default max current, it should remove the "charge_current" property from the overrides.

**Comment by firstof9** [comment]
It is using the `soft_max_current` as the value.

**Comment by firstof9** [comment]
The charge rate slider follows the charge rate as it shows in the OpenEVSE UI this is as intended.

Maybe you are looking for the `sensor.openevse_max_current` to provide the max current sensor you're looking for?

**Comment by KipK** [comment]
the charge_rate value shouldn't be settable then and is not what is used on openevse UI.
I know the api is a pain, i had some headache to find some good logics for simple needs :)

What you call charge_rate is the "pilot" in openevse

It follows on openevse UI on your side because you're not using the current shaper so pilot is not controlled by another service.
But when the current shaper run, or any another service with higher priority than override ( I think OCPP is too ) , they can control the Pilot too.

So if the number.charge_rate follows Pilot, then your setting slider will move alone following Pilot changed by the shaper itself not by the user.
That's why I had to do it differently on openevse UI. 

Here is the logic of how I've made the OpenEVSE UI main tab slider :

Changing value set the "max_current" property as an Override.
If user manually set it back to 32A ( = "max_current_soft" from the /config ) , it then remove the override property as it is useless to keep it. 
The displayed value in the slider is the "charge_current" property from the /override. If it's not present then it takes "max_current_soft" from /config

**Comment by KipK** [comment]
This means on your plugin 

- number.charge_rate perhaps should then be renamed in number.charge_current and use the logic above by taking its state on /override endpoint, charge_current prop, and if no override from /status "max_current" and not from Pilot value
- pilot value should be exposed as sensor ( and not number.charge_rate ) aka sensor.openevse_pilot 
- sensor.openevse_max_amps and sensor.openevse_max_current seems to be the same value , are they ? 
those are not the max amp value you set from number_charge rate but comes from the configuration (  max_current_soft ), perhaps they should be rename to sensor/openevse_config_max_current to claerly indicate it's origin. ( Same for configuration value if they are exposed but i don't think  so )

**Comment by firstof9** [comment]
> * sensor.openevse_max_amps and sensor.openevse_max_current seems to be the same value , are they ?

No

Max Amps is the hardware max as sent by OpenEVSE.

Charge rate controls the charge rate as indicated in the Web UI:
![image](https://github.com/user-attachments/assets/359db45f-605b-42e4-921d-bd2d6e6e343b)


Max Current is indicated here:
![image](https://github.com/user-attachments/assets/640a7575-b076-4721-8bb1-867aededd13b)

When your shaper is active does the charge rate from the first screen move around? Mine does when I have PV divert set with eco mode going.

**Comment by KipK** [comment]
I have made the openEVSE UI mate ;)


Yes when shaper change the available current, the slider charge rate change on HA, not on openevse UI ( because it works as I explained above ). 

I know it's as confuse as the openevse API is , would you want we chat about this directly , that would be easier to explain if I was not clear.

**Comment by KipK** [comment]
> Charge rate controls the charge rate as indicated in the Web UI:

It is not reallly. On your side you see it because as explained there's no service above. The slide rfrom your first screen ( the max current from main tab ) , is working like detailed above. It creates /override with charge_current property. 
The number.charge_rate  creates an override like on the UI, but the value displays pilot not the /override property that has been set.

**Comment by KipK** [comment]
Ok i get it, I have tested by simulating PV data:

![image](https://github.com/user-attachments/assets/8b281e40-b144-4a64-931d-26485a9fa215)

On PV divert case, it's normal you see the slider following the available current, as Divert control the charge_current property too.
( Shaper control the max_current prop )
When divert as set the charge_current, it has bigger priority than override in eco mode.
Then on the OpenEVSE UI, the slider is locked, you can't set the value, as it's useless since the PV use it. 
You can see the little tooltip above, mentionning this value is now controlled by Divert, and the disabled slider.

But with shaper it's different, shaper is a security feature, it set the max_current, but you still can set the charge_current. 
It means until shaper keep max_current above the charge_current setted by override, charge_current is used as pilot value.
But when max_current from shaper goes under this value, the pilot can goes above. Still charge_current prop is active, but superseded by the max value. 

On UI side, the charge_current slider is still usable then as the max_current set by the shaper follow the current available it calculated

**Comment by firstof9** [comment]
> The max current from the second screen shouldn't be accessible from HA anyway, as it's a one time configuration. This one is written to the flash so if people use it on their script it can kill the flash if there's lot of changes.

This is why it's not configurable via HA and it only shows up under the diagnostics area.

> You can see the little tooltip just under, mentionning this value is now controlled by Divert, and the disabled slider.

I can mimic this in the integration as well.

Part of the issue is the API docs for the shaper values doesn't exist either. I'm trying to work off of what's available on https://openevse.stoplight.io/docs/openevse-wifi-v4/e3153e2367cb1-open-evse-wi-fi-api and then anything else I have to dig through the firmware code.

**Comment by KipK** [comment]
Don't hesitate to bump me if you need help or clarification on the API. I had to leave for a year the openevse project because of personal life changes, but I still have it in mind. Spent so much time on this. 

I can make you some few scheme to summerise the logic used on UI and how it's handled on OpenEvse.
I'll need first to point the values and actions exposed on your integration with those in openevse first.

Reading what I've written here is really not clear :)

**Comment by firstof9** [comment]
I guess I need to see if there's a way to set the `shaper_max_pwr` via the API.

**Comment by KipK** [comment]
shaper max power is a fixed value from the conf , if you meant shaper_live_pwr, you already can feed it over the api with POST on /status :  
` {"shaper_live_pwr": xxx}`
