### ISSUE TITLE
2024.11.0 Depreciation Warning

### ISSUE THREAD

**Issue by Nick425321** [firstof9/openevse#398]
### The problem

The following depreciation warning was introduced by HA core 2024.11.0:

Logger: homeassistant.core
Source: helpers/deprecation.py:222
First occurred: 05:42:52 (1 occurrences)
Last logged: 05:42:52

Config was used from openevse, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'openevse' custom integration

### What version of Home Assistant?

2024.11.0

### What version of OpenEVSE?

2.1.46

**Comment by firstof9** [comment]
This is already fixed in 2.1.47.
Thanks!
