### ISSUE TITLE
Feature Request: Voltage Set

### ISSUE THREAD

**Issue by dakaix** [firstof9/openevse#53]
Great work on this component @firstof9! This is a feature request for an ability to have HA set the current voltage on the OpenEVSE.

This is available via RAPI, and since there's no voltage measurement in the OpenEVSE controller dynamically setting it externally is the only way to have an accurate Power (W) measurement.

See OpenEVSE KB: https://openev.freshdesk.com/support/solutions/articles/6000249626-voltage-displays-240-how-do-i-set-to-something-different-

I'm looking to use an automation to have that value pushed from my existing power monitoring feed in HA.

**Comment by firstof9** [comment]
As RAPI is being deprecated, we'd need some way to set this via the HTTP API.

**Comment by HLFCode** [comment]
Set the voltage via mqtt directly from HA with an automation (service: mqtt.publish).
The default topic is emon/emonpi/vrms and is part of the openevse solar divert functionality. 
Works for me...
