### ISSUE TITLE
Divert mode select doesn't work

### ISSUE THREAD

**Issue by ruimarinho** [firstof9/openevse#57]
Hi @firstof9,

Just updated to the latest version (2.1.3) and the divert mode select still doesn't set the right mode when any option is selected. Curiously, listening for updates on changes from the web UI itself works great.

I'm on wifi version 4.1.4.dev, Firmware: 7.1.3.3P and Home Assistant 2022.08.6.

Let me know how I can help debug this.

**Comment by ruimarinho** [comment]
Just noticed my `divert_active` binary sensor is also showing as `off` when divert mode is enabled.

**Comment by firstof9** [comment]
Yes, I have to look at it again. I don't think the API is working quite right for divert, I may need to submit a issue to OpenEVSE.

**Comment by graememk** [comment]
Possible workaround in the meantime : 
Use MQTT to  control the Divertmode <base-topic>/divertmode/set [1 | 2] : enable (1)/ disable (2) divert mode

Toggling it in the OpenEVSE webpage changes the selection in HA.

**Comment by ruimarinho** [comment]
I'm still using this workaround on the latest version of OpenEVSE WiFi.

**Comment by clowrey** [comment]
I've been having trouble getting MQTT to change the divert mode too, maybe just me though... That's what led me to this awesome HA integration, I was trying to do everything through Node-Red before.

**Comment by firstof9** [comment]
Divert mode has been updated to `fast` / `eco` and a toggle added to enable/disable the `Solar PV Divert` feature.
