### ISSUE TITLE
Naming of sensors

### ISSUE THREAD

**Issue by ruimarinho** [firstof9/openevse#58]
Hi @firstof9,

I suggest removing the underscore from sensors' names and using a space character instead. Home Assistant will automatically remove the "device name" prefix if that structure is used. I believe the name attribute is being set here https://github.com/firstof9/openevse/blob/main/custom_components/openevse/sensor.py#L52.

Instead of `openevse_Ambient Temperature`, one would simply see `Ambient Temperature`.

What do you think?

**Comment by firstof9** [comment]
This was on the todo list, feel free to submit a PR for the change.

**Comment by firstof9** [comment]
fixed in #59
