### ISSUE TITLE
Again the integration not show in the add list

### ISSUE THREAD

**Issue by pepelillo** [firstof9/openevse#65]
Same issue but different log than the closed issue
Logger: openevsehttp
Source: custom_components/openevse/config_flow.py:60
Integration: OpenEVSE
First occurred: 10:48:32 (2 occurrences)
Last logged: 10:48:32

Non JSON response:
Authentication error:

But How can I configure authentication if I can't add the integration in the list and configure it?

**Comment by firstof9** [comment]
Find the proper error logged in `home-assistant.log`

**Comment by pepelillo** [comment]
Solved......Some kind of interaction with the ocpp integration (was disabled but I need to uninstall it), now it is showed in list.
Thanks

**Comment by firstof9** [comment]
Weird
