### ISSUE TITLE
Energy Limit Feature

### ISSUE THREAD

**Issue by mattbruman** [firstof9/openevse#66]
Is there any way to get the option to set a Energy Limit? 

Say you are planning a extra trip but don't need the battery fully charged just need a few extra miles and charging during the day is more expensive if you have a power plan that is cheaper at night.

I don't mind sending this as MQTT if you can point me to the proper Topic and Payloads.

Thanks for this btw as I just updated HA and everything I had working before from another dev completely stopped working.

**Comment by firstof9** [comment]
You can set a limit from the OpenEVSE UI AFAIK

**Comment by mattbruman** [comment]
Yeah but in my previous setup before it broke I have a multifunction remote with labels on it that say 25%, 50% 100% charge that I automated with HA to quickly set a charge level and charge that amount. 

Is there a way to still do that with the web API or MQTT?

**Comment by firstof9** [comment]
I'd have to check the http api, and I'm not 100% sure with MQTT

**Comment by mattbruman** [comment]
That's disappointing that it wasn't added to the API since it could be done with RAPI commands

**Comment by firstof9** [comment]
I see it in the HTTP API documentation as "Not yet implemented" so maybe it's on their roadmap.

**Comment by mattbruman** [comment]
![image](https://github.com/firstof9/openevse/assets/43623584/9f213d98-416e-44e0-8109-4937a6dab151)
This is now showing in the UI with the newest firmware. Any hint of it being able to port over to HA?

**Comment by firstof9** [comment]
Please see #285
