### ISSUE TITLE
Calling `switch.turn_off` on `switch.openevse_sleep_mode` toggles sleep mode

### ISSUE THREAD

**Issue by Cadair** [firstof9/openevse#99]
I was trying to run this down with the latest beta when I hit #97 but I can definitely reproduce this with 2.1.6.

If the sleep mode switch is off (and the car is disconnected) calling the switch turn off service on the switch again should do nothing, but it appears to put the charger into sleep mode (i.e. it toggles rather than turns off).

**Comment by firstof9** [comment]
Please confirm this is working as expected now, I tested it on my dev instance of HA and it worked correctly.
If it's fixed feel free to close the issue. Thanks!

**Comment by Cadair** [comment]
Yes it works great now, thanks!
